[#sec:intro:glossary]
### Glossary

.Glossary of terms
[cols="1,4a",]
|===
| *Term* | *Definition*

| ASIL
| Automotive Safety Integrity Level.
  Risk classification scheme defined by the ISO 26262 cite:[iso26262:2018]
  identifying four ASILs ranging from the lowest to the highest integrity
  requirements: ASIL A, ASIL B, ASIL C and ASIL D.

| CAST
| Certification Authorities Software Team.
  CAST is an international group of aviation certification and regulatory
  authority representatives.
  Inactive since 2016.

| CMO
| Cache Memory Operations (task group).

| DAL
| Design Assurance Level, term used in avionics systems to define the safety
level.
Safety levels are identified with letter, from A to E, with DAL A identifying
the highest safety requirements and DAL E for no safety requirement.

| Determinism
| Capability of a system that given the same input it always generates the same
outputs while passing through the same intermediate states, no matter how many
times the same input is presented to the system.
In safety critical systems determinism typically also applies to the time, and
other non-functional properties, the system requires to process the input, i.e.
capability of the system to always process the input in a fixed amount of time
no matter when the input is presented to the system.

| DMA
| Direct-Memory Access.

| EASA
| European Union Aviation Safety Agency.

| ECC
| Error Code Correction.

| ECSS
| European Center for Space Standardization.

| ESA
| European Space Agency.

| FAA
| Federal Aviation Agency.

| Fault, error and failure
| These terms refer to the series of events that can put a system malfunctioning
  state, which in the case of safety critical systems might cause hazard to the
  environment or human life.
  Depending on the domain (software, automotive, avionics, etc.) these terms
  differ.
  For example, in the automotive domain (ISO 26262) a _fault_ is an
  abnormal condition that can cause an element to fail, which can cause an
  _error_ (a discrepancy between a computed, observed or measured
  value/condition and the true theoretical value/condition) which can ultimately
  provoke a permanent or transient _failure_ on the system, that is the
  termination of the system intended behavior.
  In the software domain, an _error_ refers to a software error (e.g. a bug)
  that can cause a _fault_ which ultimately causes a system _failure_.

| Interference
| Interference refers to the impact an event or process can have in the
execution of another process in a processor.
The interference can be observed as a variation on the process execution time
and it is typically due to the use processor shared resources.

| Hypervisor
| Thin software layer that provides abstraction of hardware to one or several
operating systems, by allowing them to run on the same host hardware.

| ID
| Identifier.

| IO
| Input/Output.

| IOATC
| IOMMU Address Translation Cache.

| IOMMU
| Input/Output Memory Management Unit.

| IPC
| Instructions Per Cycle.

| ISO
| International Standards Office.

| LRU
| _Least-recently used_ algorithm.

| MCU
| Micro-Controller Unit.

| MMU
| Memory Management Unit.

| MSI
| Message Signaled Interrupt.

| OS
| Operating System.

| PLRU
| _Pseudo least-recently used_ algorithm.

| PMC
| Performance Monitoring Counter, also referred as Performance Counter.

| QoS
| Quality of Service.

| RTOS
| Real-Time Operating System.

| SECDED
| Single Error Correction Double Error Detection.

| SLA
| Service Level Agreement.

| SMP
| Symmetric Multi-Processing.

| TCM
| Tightly Coupled Memory. Also known as Closely-Coupled Memories (CCMs),
  scratchpad memories, local memories, Tightly Integrated Memories, or local
  memories.

| WCET
| Worst-Case Exection Time.
  In a computer system the WCET is the maximum time a task could take to
  execute.

|===

[WARNING]
.Other possible terms
====
Do we need to add the following terms to the glossary:

* RCID/MCID

====
